#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Order_Management_API/Order_Management_API.csproj", "Order_Management_API/"]
RUN dotnet restore "Order_Management_API/Order_Management_API.csproj"
COPY . .
WORKDIR "/src/Order_Management_API"
RUN dotnet build "Order_Management_API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Order_Management_API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Order_Management_API.dll"]